# Generated by Django 5.0.3 on 2024-03-31 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
                ('PostID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.post')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
                ('PostID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='posts.post')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='posts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PostID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save', to='posts.post')),
                ('UserID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='save', to='posts.user')),
            ],
        ),
    ]
